### ISSUE TITLE
Improvement - set default root namespace for managed projects

### ISSUE THREAD

**Issue by alexbereznikov** [Aschratt/DotNetWithCMake#2]
I'm trying to build a managed library with CMake using templates from this repository. Everything is OK but I've noticed that root namespace is not set when VS project is generated. This is not critical, but differs from the default VS behavior when the new project is created (by default, root namespace is equal to the project name). At least on my machine missing root namespace leads to confusing warnings inside IDE complaining that "Namespace does not correspond to file location", which goes away with the correct root namespace.

My suggestion is to add the following line to `CMakeLists.txt`:
`set_property(TARGET MyAwesomeTarget PROPERTY VS_GLOBAL_ROOTNAMESPACE ${PROJECT_NAME})`

**Comment by alexbereznikov** [comment]
@Aschratt If you don't mind I'm ready to go ahead and add this line into all `CMakeLists.txt`

**Comment by crud89** [comment]
Can you post which warnings you are receiving? I think the warning you are referring to is simply a style-hint to ensure that you put the files in a similar file hierarchy as you structure your namespaces. Also, if I am not mistaken, this warning isn't generated for C++/CLI projects, isn't it?

However, I agree hat the root namespace is actually an important property. It may even be required in certain scenarios. I had to add the property in a project that contained embedded resources, since some built-in .NET types otherwise were not able to properly resolve resource names (e.g. Windows Forms `Cursor`).

If you want to contribute: sure! Feel free to open a PR when you're done. 🙂

**Comment by alexbereznikov** [comment]
Yep, I've revisited the warnings and looks like that was because of StyleCop.

**Comment by alexbereznikov** [comment]
@Aschratt Done, please take a look at #3
